Add remove function
queryverse/NamedTupleUtilities.jl pull request #3
Opened 2018-09-25 01:09 UTC by TonyLianLong

I added the remove function. Tests needed to be written.

2018-09-30 04:18 UTC, TonyLianLong commented
I also added the `range` function with the tests.

2018-09-30 04:51 UTC, TonyLianLong commented
Added `rename` function with tests(https://github.com/queryverse/NamedTupleUtilities.jl/issues/4).

2018-10-04 23:03 UTC, davidanthoff requested changes
Excellent, this is really great!

I've added a lot of nitpicking comments. I think we could merge your original version, as it strikes me as correct. But I think it might make sense that I generally give this kind of detailed feedback, it might help you guys get more familiar with general julia programming tricks!

2018-10-04 23:03 UTC, davidanthoff commented on src/NamedTupleUtilities.jl
> +        vals = Any[vals..., :(getfield(a, $(QuoteNode(n))))]
Generally, to add an element to a vector, use ``push!(array, val)``, so here for example ``push!(vals, :(getfield(a, $(QuoteNode(n)))))``.

2018-10-04 23:03 UTC, davidanthoff commented on src/NamedTupleUtilities.jl
> +    names = ()
Use a vector here.

2018-10-04 23:03 UTC, davidanthoff commented on src/NamedTupleUtilities.jl
> +    vals = Any[]
Type these vectors.

2018-10-04 23:03 UTC, davidanthoff commented on src/NamedTupleUtilities.jl
> +    :( NamedTuple{$names,$types}(($(vals...),)) )
Use ``return``.

2018-10-07 17:06 UTC, TonyLianLong commented
I changed the style of the code and also added `startswith`, `endswith`, and `occursin` to it.

2018-10-09 22:16 UTC, davidanthoff approved these changes

2018-10-09 22:16 UTC, merged

2018-10-09 22:16 UTC, davidanthoff commented
Hurray!